// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArxkx1VLwXzQehlobKgpKlc8IL2In7PHk',
    appId: '1:740495370062:web:fb67b1b52366d37052e01f',
    messagingSenderId: '740495370062',
    projectId: 'threads-clone-c9f53',
    authDomain: 'threads-clone-c9f53.firebaseapp.com',
    storageBucket: 'threads-clone-c9f53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPBzQFIsQcjgkLwcgi3A8RKejZizsJ-z0',
    appId: '1:740495370062:android:9bc3c8199fa96a4052e01f',
    messagingSenderId: '740495370062',
    projectId: 'threads-clone-c9f53',
    storageBucket: 'threads-clone-c9f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhMBSBTktBOZwSdsQW4LdZBPnRpnX0fQ',
    appId: '1:740495370062:ios:580b0df92cb4c03252e01f',
    messagingSenderId: '740495370062',
    projectId: 'threads-clone-c9f53',
    storageBucket: 'threads-clone-c9f53.appspot.com',
    iosBundleId: 'com.kdy.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArhMBSBTktBOZwSdsQW4LdZBPnRpnX0fQ',
    appId: '1:740495370062:ios:7d0d81ddff6f9bd752e01f',
    messagingSenderId: '740495370062',
    projectId: 'threads-clone-c9f53',
    storageBucket: 'threads-clone-c9f53.appspot.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
